package.json
pnpm-lock.yaml

Move @polkadot/api and @polkadot/types to peerDependencies

---

package.json
pnpm-lock.yaml

Mentioned in: #18 , #23 
Will be released in v 0.0.27

Move all Polkadot dependencies to peer dependencies 🔧

---

package.json
pnpm-lock.yaml

:arrow_up: update @polkadot/packages

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
package.json

This pull request introduces a GitHub Actions pipeline for automating the deployment of our npm package to the npmjs registry. The pipeline is named "Publish Package to npmjs" and it gets triggered on every push event that contains any kind of tag ('*').
The pipeline uses a set of predefined actions to set up a reliable and consistent environment for the package deployment process. It runs on the latest version of Ubuntu and grants read permissions for contents and write permissions for packages.
Here are the key steps in this pipeline:
1. **actions/checkout@v3**: Checks out the repository code at the latest commit.
2. **actions/setup-node@v3**: Sets up a Node.js environment using version 16.
3. **pnpm/action-setup@v2**: Sets up pnpm package manager.
4. **pnpm install**: Installs all …

Setup CD to npmjs registry on every tag push

---

src/pallets/xcmPallet/transfer.ts

fix issue
* #40 
fix by passing ```destination```
to 
1. createHeaderPolkadotXCM
2. handleAddress
3. createCurrencySpecification
tested in local env in [kodadot](https://kodadot.xyz/teleport-bridge)

🔧 transferRelayToPara bug when transfer to Basilisk

---

src/nodes/PolkadotXCMTransferImpl.ts
src/nodes/XTokensTransferImpl.ts
src/pallets/builder/builders/Builder.test.ts
src/pallets/builder/builders/Builder.ts
src/pallets/builder/builders/RelayToParaBuilder.ts
src/pallets/xcmPallet/transfer.ts
src/types.ts
src/utils.ts

PR prepares Relay to Para scenario for XCM API

Add relay to para function for api

---

package.json
pnpm-lock.yaml

Fix vite security vulnerability

---

package.json
pnpm-lock.yaml

Fix @polkadot/apps-config unmet peer dependency warnings ⚙️

---

README.md
src/nodes/ParachainNode.ts
src/pallets/assets/assetsUtils.test.ts
src/pallets/assets/assetsUtils.ts
src/pallets/xcmPallet/transfer.ts
src/types.ts

Fix handling of big asset ids 🔩

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
package.json

Cleanup package.json scripts ✨

---

src/nodes/ParachainNode.ts
src/nodes/supported/ComposableFinance.ts
src/nodes/supported/Manta.ts
src/nodes/supported/Quartz.ts
src/pallets/xcmPallet/transfer.test.ts
src/pallets/xcmPallet/transfer.ts

Changes:
- Add flag to Node class to disable asset checking for specific nodes
- Update para to para transfer tests
- Fixes #80

Update transfer pallets for parachains 📦

---

src/nodes/ParachainNode.ts
src/nodes/supported/Astar.ts
src/nodes/supported/Shiden.ts
src/pallets/assets/assets.ts
src/pallets/builder/builders/Builder.test.ts
src/pallets/builder/builders/Builder.ts
src/pallets/builder/builders/ParaToParaBuilder.ts
src/pallets/builder/builders/RelayToParaBuilder.ts
src/pallets/xcmPallet/transfer.test.ts
src/pallets/xcmPallet/transfer.ts
src/pallets/xcmPallet/utils.ts
src/types.ts

Closes https://github.com/paraspell/xcm-sdk/issues/97

Add ability to customize ParaID 🪛

---

src/nodes/ParachainNode.ts
src/nodes/supported/Astar.ts
src/nodes/supported/Moonbeam.ts
src/nodes/supported/Moonriver.ts
src/nodes/supported/Shiden.ts
src/pallets/xcmPallet/utils.ts
src/types.ts
src/utils.ts

Refactor createHeaderPolkadotXCM function

---

reviewpad.yml

Add Reviewpad configuration file.

chore: Add PR AI summaries

---

.eslintrc.json
package.json
pnpm-lock.yaml
src/pallets/hrmp/channelsClose.ts
src/pallets/parasSudoWrapper/channels.ts
src/pallets/xcmPallet/transfer.ts
src/pallets/xyk/xyk.ts

refactor: Setup ESLint rule to prefer arrow functions ➡️

---

e2e/xcm.test.ts
src/maps/assets.json
src/maps/consts.ts
src/maps/existential-deposits.json
src/maps/pallets.json
src/nodes/supported/CoretimeKusama.ts
src/utils.test.ts

Closes #148 
The implementation was tested on Rococo and works well.

Adding rococo coretime chain

---

.github/workflows/ci.yml

Closes https://github.com/paraspell/xcm-tools/issues/184

fix: Remove unused branch from Github action

---

apps/playground/package.json
apps/playground/src/App.tsx
apps/playground/src/components/OutputAlert.tsx
apps/playground/src/components/analyser/AnalyserForm.tsx
apps/playground/src/routes/XcmAnalyserSandbox.tsx
pnpm-lock.yaml

feat: Add XCM Analyser to Playground ✨

---

packages/sdk/scripts/scriptUtils.ts

fix: Fix maps JSON print width

---

apps/playground/package.json
apps/playground/src/components/asset-claim/AssetClaim.tsx
apps/playground/src/components/asset-claim/AssetClaimForm.tsx
apps/playground/src/routes/XcmSdkSandbox.tsx
pnpm-lock.yaml

feat: Add asset claim to playground ✨

---

packages/xcm-router/src/dexNodes/Acala/AcalaDex.integration.test.ts
packages/xcm-router/src/dexNodes/Acala/utils.test.ts
packages/xcm-router/src/dexNodes/Bifrost/BifrostDex.integration.test.ts
packages/xcm-router/src/dexNodes/HydraDx/HydraDxDex.integration.test.ts
packages/xcm-router/src/dexNodes/Interlay/InterlayDex.integration.test.ts
packages/xcm-router/src/transfer/buildTransferExtrinsics.test.ts
packages/xcm-router/src/transfer/selectBestExchange.test.ts
packages/xcm-router/src/transfer/swap.test.ts
packages/xcm-router/src/transfer/transfer.integration.test.ts

…for small amount error
Closes #244

XCM Overhaul PR #3 - Reduce unit tests code duplication

---

apps/xcm-api/README.md
packages/xcm-router/package.json

build: Update all package commands to use pnpm

---

apps/playground/src/App.tsx
apps/playground/src/components/RouterTransferForm.tsx
apps/playground/src/components/TransferInfo.tsx
apps/playground/src/components/XcmTransfer.tsx
apps/playground/src/components/asset-claim/AssetClaim.tsx
apps/playground/src/components/assets/AssetsQueries.tsx
apps/playground/src/components/channels/ChannelsQueries.tsx
apps/playground/src/components/eth-bridge/EthBridgeTransfer.tsx
apps/playground/src/components/pallets/PalletsQueries.tsx
apps/playground/src/providers/ThemeContext.ts
apps/playground/src/routes/RouterTransferPage.tsx
apps/playground/src/theme/themeConfig.ts
apps/visualizator-fe/src/components/SendXcm/SendXcm.tsx

refactor: Fix all instances of no-misused-promises linter error 👨‍💻

---

apps/playground/src/components/CurrencySelection.tsx
apps/playground/src/components/RouterTransferForm.tsx
apps/playground/src/components/TransferForm.tsx
apps/playground/src/components/XcmTransfer.tsx
apps/playground/src/components/eth-bridge/EthBridgeTransfer.tsx
apps/playground/src/components/eth-bridge/EthBridgeTransferForm.tsx
apps/playground/src/hooks/useCurrencyOptions.ts
apps/xcm-api/test/app.e2e-spec.ts
packages/sdk/src/errors/IncompatibleNodesError.ts
packages/sdk/src/maps/assets.json
packages/sdk/src/nodes/supported/Astar.ts
packages/sdk/src/nodes/supported/Shiden.ts
packages/sdk/src/pallets/assets/assets.ts
packages/sdk/src/pallets/assets/assetsUtils.test.ts
packages/sdk/src/pallets/assets/assetsUtils.ts
packages/sdk/src/pallets/assets/getTransferInfo.ts
packages/sdk/src/pallets/xcmPallet/transfer.ts
packages/sdk/src/types/TAssets.ts
packages/sdk/src/utils.ts
packages/xcm-router/src/assets/assets.ts
packages/xcm-router/src/transfer/selectBestExchange.ts
packages/xcm-router/src/transfer/transfer.ts
packages/xcm-router/src/transfer/utils.ts

feat: Add Select component for selecting assets

---

apps/landing-page/package.json
apps/landing-page/src/components/Faq/Faq.tsx
apps/landing-page/src/components/Footer/Footer.tsx
apps/landing-page/src/components/TryIt/TryIt.tsx
apps/landing-page/vite.config.ts
apps/visualizator-fe/src/components/EcosystemSelect/EcosystemSelect.tsx
eslint.config.js
package.json
pnpm-lock.yaml

build: Add ESlint React plugin 🔨

---

apps/playground/src/components/EthAccountsModal.tsx
apps/playground/src/components/RouterTransferForm.tsx
packages/xcm-router/src/transfer/selectBestExchange.ts
packages/xcm-router/src/transfer/transfer.test.ts
packages/xcm-router/src/transfer/transfer.ts
packages/xcm-router/src/transfer/transferFromEthereum.test.ts
packages/xcm-router/src/transfer/transferFromEthereum.ts
packages/xcm-router/src/transfer/transferToEthereum.test.ts
packages/xcm-router/src/transfer/transferToEthereum.ts
packages/xcm-router/src/transfer/utils.ts
packages/xcm-router/src/types.ts

feat(xcm-router): Add Snowbridge transfers support ❄️

---

apps/xcm-api/src/x-transfer/dto/XTransferDto.ts
apps/xcm-api/src/xcm-analyser/dto/xcm-analyser.dto.ts
packages/xcm-analyser/src/types.ts

fix: Remove duplicated ZOD validation code 🔨

---

.github/workflows/ci.yml
codecov.yml
turbo.json

ci: Setup Codecov carry-forward flags 🚩

---

packages/sdk/scripts/assets/fetchAssets.ts
packages/sdk/src/maps/assets.json
packages/sdk/src/nodes/ParachainNode.test.ts
packages/sdk/src/nodes/ParachainNode.ts
packages/sdk/src/types/TAssets.ts
packages/sdk/src/utils/deepEqual.test.ts
packages/sdk/src/utils/deepEqual.ts
packages/sdk/src/utils/verifyMultilocation.test.ts
packages/sdk/src/utils/verifyMultilocation.ts

feat(sdk): Add foreignAssets pallet multi-location checks

---

packages/sdk/package.json
packages/sdk/src/nodes/supported/AssetHubPolkadot.test.ts
packages/sdk/src/nodes/supported/CoretimePolkadot.test.ts
pnpm-lock.yaml

build(sdk): Setup more benevolent peer dependencies 📦

---

apps/xcm-api/src/analytics/EventName.ts
apps/xcm-api/src/x-transfer/dto/XTransferBatchDto.ts
apps/xcm-api/src/x-transfer/x-transfer.controller.test.ts
apps/xcm-api/src/x-transfer/x-transfer.controller.ts
apps/xcm-api/src/x-transfer/x-transfer.service.test.ts
apps/xcm-api/src/x-transfer/x-transfer.service.ts
apps/xcm-api/test/app.e2e-spec.ts

feat(xcm-api): Add support for transfer batching ⛓️

---

apps/playground/src/components/analyser/AnalyserForm.tsx
apps/playground/src/routes/XcmAnalyserSandbox.tsx

feat(playground): Add useApi checkbox to XcmAnalyser form ✅

---

packages/sdk/src/builder/builders/AssetClaimBuilder.ts
packages/sdk/src/builder/builders/BatchTransactionManager.test.ts
packages/sdk/src/builder/builders/BatchTransactionManager.ts
packages/sdk/src/builder/builders/Builder.ts
packages/sdk/src/builder/builders/IBatchBuilder.ts
packages/sdk/src/builder/builders/ParaToParaBuilder.ts
packages/sdk/src/builder/builders/ParaToRelayBuilder.ts
packages/sdk/src/builder/builders/RelayToParaBuilder.ts
packages/sdk/src/pallets/assets/asset-claim/assetClaim.ts
packages/sdk/src/pallets/assets/asset-claim/buildClaimAssetsInput.test.ts
packages/sdk/src/pallets/assets/asset-claim/buildClaimAssetsInput.ts
packages/sdk/src/pallets/xcmPallet/transfer.ts
packages/sdk/src/types/TAssetClaim.ts
packages/sdk/src/types/TTransfer.ts

refactor(sdk): Generalize Builder class

---

apps/playground/src/components/XcmTransfer.tsx
packages/sdk/scripts/assets/fetchAssets.ts
packages/sdk/src/maps/assets.json
packages/sdk/src/nodes/supported/BifrostPolkadot.test.ts
packages/sdk/src/nodes/supported/BifrostPolkadot.ts
packages/sdk/src/pallets/assets/assets.ts
packages/sdk/src/pallets/assets/assetsUtils.ts
packages/sdk/src/pallets/assets/getAssetBySymbolOrId.test.ts
packages/sdk/src/pallets/assets/getOriginFeeDetails.test.ts
packages/sdk/src/pallets/assets/getOriginFeeDetails.ts
packages/sdk/src/pallets/assets/getSupportedAssets.ts
packages/sdk/src/pallets/assets/transfer-info/getTransferInfo.ts
packages/sdk/src/pallets/xcmPallet/transfer.ts
packages/sdk/src/papi/PapiApi.ts
packages/sdk/src/papi/assets.ts
packages/sdk/src/pjs/assets.ts
packages/sdk/src/types/TBalance.ts

fix(sdk): Fix Moonbeam 'xc' prefix handling 🔧

---

packages/sdk/README.md
packages/sdk/e2e/xcm-papi.test.ts
packages/sdk/src/api/IPolkadotApi.ts
packages/sdk/src/nodes/xTokens/XTokensTransferImpl.ts
packages/sdk/src/pallets/assets/getSupportedAssets.ts
packages/sdk/src/pallets/xcmPallet/transfer.ts
packages/sdk/src/papi/PapiApi.ts
packages/sdk/src/papi/assets.test.ts
packages/sdk/src/papi/assets.ts
packages/sdk/src/papi/builder.test.ts
packages/sdk/src/papi/builder.ts
packages/sdk/src/papi/transfer.test.ts
packages/sdk/src/papi/transfer.ts
packages/sdk/src/papi/types.ts
packages/sdk/src/papi/utils.test.ts
packages/sdk/src/papi/utils.ts
packages/sdk/src/pjs/PolkadotJsApi.test.ts
packages/sdk/src/pjs/PolkadotJsApi.ts
packages/sdk/src/pjs/assets.ts
packages/sdk/src/pjs/builder.ts
packages/sdk/src/pjs/transfer.test.ts
packages/sdk/src/pjs/transfer.ts
packages/sdk/src/pjs/types.ts
packages/sdk/src/pjs/utils.test.ts
packages/sdk/src/pjs/utils.ts
packages/sdk/src/types/TApi.ts

feat(sdk): Allow to pass RPC url to create API client ✨

---

apps/playground/src/components/XcmTransfer.tsx
packages/sdk/package.json
packages/sdk/scripts/assets/fetchAssets.ts
packages/sdk/scripts/assets/fetchEthereumAssets.ts
packages/sdk/scripts/assets/nodeToQueryMap.ts
packages/sdk/src/maps/assets.json
packages/sdk/src/nodes/supported/AssetHubPolkadot.test.ts
packages/sdk/src/nodes/supported/AssetHubPolkadot.ts
packages/sdk/src/nodes/supported/Hydration.ts
packages/sdk/src/pallets/assets/assets.test.ts
packages/sdk/src/pallets/assets/assets.ts
packages/sdk/src/pallets/assets/assetsUtils.ts
packages/sdk/src/pallets/assets/balance/getBalanceForeignPolkadotXcm.test.ts
packages/sdk/src/pallets/assets/balance/getBalanceForeignPolkadotXcm.ts
packages/sdk/src/pallets/assets/getAssetBySymbolOrId.test.ts
packages/sdk/src/pallets/assets/getAssetBySymbolOrId.ts
packages/sdk/src/pallets/assets/getOriginFeeDetails.test.ts
packages/sdk/src/pallets/assets/getOriginFeeDetails.ts
packages/sdk/src/pallets/assets/getSupportedAssets.test.ts
packages/sdk/src/pallets/assets/getSupportedAssets.ts
packages/sdk/src/pallets/assets/transfer-info/getTransferInfo.ts
packages/sdk/src/types/TAssets.ts
packages/sdk/src/types/TBalance.ts
packages/sdk/src/utils/multiLocation/createEthereumTokenLocation.test.ts
packages/sdk/src/utils/multiLocation/createEthereumTokenLocation.ts
pnpm-lock.yaml

fix(sdk): Fix Snowbridge asset selection ✨

---

apps/site/src/components/HeroCards/HeroCards.tsx
apps/site/src/components/XcmApi/XcmApi.tsx
apps/site/src/components/XcmRouter/XcmRouter.tsx
apps/site/src/components/XcmSdk/XcmSdk.tsx

The following PR fixes 2 things on the landing page:
- Adds transparent hero cards: Closes #476
- Adds template project buttons: Closes #444

Update landing page 🛬

---

apps/xcm-api/src/x-transfer/dto/XTransferDto.ts
apps/xcm-api/src/x-transfer/x-transfer.service.test.ts
apps/xcm-api/src/x-transfer/x-transfer.service.ts
apps/xcm-api/test/app.e2e-spec.ts
packages/sdk-core/src/builder/Builder.ts
packages/sdk-core/src/nodes/ParachainNode.ts
packages/sdk-core/src/pallets/polkadotXcm/PolkadotXCMTransferImpl.ts
packages/sdk-core/src/pallets/xTokens/XTokensTransferImpl.ts
packages/sdk-core/src/pallets/xTransfer/XTransferTransferImpl.ts
packages/sdk-core/src/transfer/transfer.ts
packages/sdk-core/src/transfer/transferRelayToPara.ts
packages/sdk-core/src/types/TBuilder.ts
packages/sdk-core/src/types/TTransfer.ts
packages/sdk-pjs/README.md
packages/sdk/README.md

feat(sdk-core): Add support for pallet / method override ✨

---

packages/sdk-core/package.json
packages/sdk-pjs/package.json
packages/sdk/package.json
packages/xcm-analyser/package.json
packages/xcm-router/package.json

fix: Fix package json warnings 🔧

---

apps/xcm-api/src/x-transfer/x-transfer.service.test.ts
apps/xcm-api/src/x-transfer/x-transfer.service.ts
apps/xcm-api/test/app.e2e-spec.ts

refactor(xcm-api): Refactor x-transfer module 🛠️

---

apps/xcm-api/src/asset-claim/asset-claim.service.test.ts
apps/xcm-api/src/asset-claim/asset-claim.service.ts
apps/xcm-api/src/balance/balance.service.test.ts
apps/xcm-api/src/balance/balance.service.ts
apps/xcm-api/src/x-transfer/x-transfer.service.test.ts
apps/xcm-api/src/x-transfer/x-transfer.service.ts
packages/sdk-core/src/types/TBuilder.ts
packages/sdk-pjs/src/PolkadotJsApi.ts
packages/sdk/src/PapiApi.ts

refactor(xcm-api): Use automatic api creating ✨

---

packages/sdk-core/scripts/assets/fetchAssets.ts
packages/sdk-core/scripts/assets/fetchUniqueAssets.ts
packages/sdk-core/scripts/assets/nodeToQueryMap.ts
packages/sdk-core/src/maps/assets.json
packages/sdk-core/src/nodes/supported/Quartz.test.ts
packages/sdk-core/src/nodes/supported/Quartz.ts
packages/sdk-core/src/nodes/supported/Unique.test.ts
packages/sdk-core/src/nodes/supported/Unique.ts
packages/sdk-core/src/types/TMultiLocation.ts

fix: Add missing assets ✨

---

.github/workflows/deploy.yml
apps/playground/src/components/AssetClaim/AssetClaim.tsx
apps/playground/src/components/XcmTransfer/XcmTransfer.tsx
apps/xcm-api/src/x-transfer/x-transfer.service.ts
packages/sdk-core/src/transfer/getDryRun.test.ts
packages/sdk-core/src/transfer/getDryRun.ts
packages/sdk-pjs/src/builder.ts
packages/sdk-pjs/src/index.test.ts
packages/sdk-pjs/src/index.ts
packages/sdk/src/builder.ts
packages/sdk/src/index.test.ts
packages/sdk/src/index.ts

Closes #727 
Closes #663 
Closes #665

build(xcm-api): Enable auto-deploy ↑

---

release-please-config.json

build(xcm-router): Add XCM Router to release group 📦

---

packages/sdk-core/src/nodes/supported/Pendulum.test.ts
packages/sdk-core/src/nodes/supported/Pendulum.ts
packages/sdk-core/src/types/TCurrency.ts

Enable new routes for Pendulum.
Still need to enable Pendulum > Para - DOT & Pendulum > Relay

Enable Relay > Pendulum & Pendulum Para PEN

---

packages/assets/scripts/fetchAssets.ts
packages/assets/scripts/fetchOtherAssetsRegistry.ts
packages/assets/scripts/fetchXcmRegistry.ts
packages/assets/scripts/nodeToQueryMap.ts
packages/assets/scripts/utils.ts
packages/assets/src/maps/assets.json
packages/sdk-common/src/utils/index.ts
packages/sdk-common/src/utils/isRelayChain.test.ts
packages/sdk-common/src/utils/isRelayChain.ts
packages/sdk-core/src/builder/Builder.ts
packages/sdk-core/src/nodes/ParachainNode.ts
packages/sdk-core/src/pallets/assets/asset-claim/assetClaim.test.ts
packages/sdk-core/src/pallets/assets/asset-claim/assetClaim.ts
packages/sdk-core/src/pallets/assets/getTransferableAmount.test.ts
packages/sdk-core/src/pallets/assets/getTransferableAmount.ts
packages/sdk-core/src/pallets/xTokens/utils/getModifiedCurrencySelection.ts
packages/sdk-core/src/transfer/transfer.test.ts
packages/sdk-core/src/transfer/transfer.ts
packages/sdk-core/src/transfer/utils/determineAssetCheckEnabled.test.ts
packages/sdk-core/src/transfer/utils/determineAssetCheckEnabled.ts
packages/sdk-core/src/transfer/utils/validationUtils.test.ts
packages/sdk-core/src/transfer/utils/validationUtils.ts
packages/sdk-core/src/utils/index.ts
packages/sdk-core/src/utils/resolveParaId.test.ts
packages/sdk-core/src/utils/resolveParaId.ts

fix(assets): Add relay assets multi-locations ✨

---

apps/playground/src/components/XcmTransfer/XcmTransfer.tsx
apps/xcm-api/README.md
packages/assets/scripts/fetchAssets.ts
packages/assets/scripts/nodeToQueryMap.ts
packages/assets/src/assets/search/findAsset.test.ts
packages/assets/src/maps/assets.json
packages/sdk-core/src/nodes/ParachainNode.test.ts
packages/sdk-core/src/nodes/ParachainNode.ts
packages/sdk-core/src/nodes/supported/Astar.test.ts
packages/sdk-core/src/nodes/supported/Astar.ts
packages/sdk-core/src/nodes/supported/Darwinia.test.ts
packages/sdk-core/src/nodes/supported/Darwinia.ts
packages/sdk-core/src/nodes/supported/KiltSpiritnet.test.ts
packages/sdk-core/src/nodes/supported/KiltSpiritnet.ts
packages/sdk-pjs/README.md
packages/sdk/README.md

fix(sdk-core): Upgrade deprecated reserve_transfer_assets transfers 🪄

---

apps/playground/src/components/AssetClaim/AssetClaim.tsx
packages/sdk-core/src/pallets/assets/asset-claim/assetClaim.test.ts
packages/sdk-core/src/pallets/assets/asset-claim/assetClaim.ts

fix: Add asset claim address validation 🪄

---

.github/workflows/deploy.yml
.github/workflows/release.yml
.release-please-manifest.json
apps/xcm-api/package.json
release-please-config.json

build: Add XCM API to release please config 📦

---

apps/playground/src/components/AppShell/AppShell.tsx
apps/playground/src/components/AppShell/Header/Header.tsx
apps/playground/src/components/AssetClaim/AssetClaim.tsx
apps/playground/src/components/AssetClaim/AssetClaimForm.tsx
apps/playground/src/components/AssetsQueries/AssetsQueries.tsx
apps/playground/src/components/AssetsQueries/AssetsQueriesForm.tsx
apps/playground/src/components/EvmTransfer/EvmTransfer.tsx
apps/playground/src/components/EvmTransfer/EvmTransferForm.tsx
apps/playground/src/components/PalletsQueries/PalletsQueriesForm.tsx
apps/playground/src/components/XcmRouter/XcmRouter.tsx
apps/playground/src/components/XcmRouter/XcmRouterForm.tsx
apps/playground/src/components/XcmTransfer/XcmTransfer.tsx
apps/playground/src/components/XcmTransfer/XcmTransferForm.tsx
apps/playground/src/components/XcmUtils/XcmUtils.tsx
apps/playground/src/components/XcmUtils/XcmUtilsForm.tsx
apps/playground/src/constants/constants.ts
apps/playground/src/constants/index.ts
apps/playground/src/hooks/index.ts
apps/playground/src/hooks/useAutoFillWalletAddress.ts
apps/playground/src/hooks/useCurrencyOptions.ts
apps/playground/src/hooks/useRouterCurrencyOptions.ts
apps/playground/src/providers/WalletProvider.tsx

feat(playground): Add wallet address autofill 🪄

---

packages/assets/scripts/fetchAcalaAssets.ts
packages/assets/src/maps/assets.json

fix(assets): Add locations to Zeitgeist assets 💰

---

packages/xcm-router/package.json
packages/xcm-router/src/dexNodes/Hydration/HydrationDex.test.ts
packages/xcm-router/src/dexNodes/Hydration/HydrationDex.ts
packages/xcm-router/src/dexNodes/Hydration/utils/calculateFee.test.ts
packages/xcm-router/src/dexNodes/Hydration/utils/calculateFee.ts
packages/xcm-router/src/dexNodes/Hydration/utils/utils.test.ts
packages/xcm-router/src/dexNodes/Hydration/utils/utils.ts
pnpm-lock.yaml

build(xcm-router): Update Hydration SDK 📦

---

apps/xcm-api/package.json
apps/xcm-api/src/app.module.ts
apps/xcm-api/src/health/health.controller.spec.ts
apps/xcm-api/src/health/health.controller.ts
apps/xcm-api/src/health/health.module.ts
apps/xcm-api/src/health/health.service.spec.ts
apps/xcm-api/src/health/health.service.ts
pnpm-lock.yaml

ci(xcm-api): Add Health check module 🏥

---

packages/assets/src/assets/search/findAsset.ts
packages/assets/src/assets/search/findAssetBySymbol.ts
packages/sdk-core/e2e/generateE2eTests.ts
packages/sdk/e2e/__snapshots__/xcm.test.ts.snap
packages/sdk/e2e/utils.ts
packages/xcm-router/src/assets/getExchangeAsset.test.ts
packages/xcm-router/src/assets/getExchangeAsset.ts
packages/xcm-router/src/dexNodes/AssetHub/AssetHubDex.ts
packages/xcm-router/src/transfer/selectBestExchangeCommon.ts
packages/xcm-router/src/transfer/utils/resolveAssets.test.ts
packages/xcm-router/src/transfer/utils/resolveAssets.ts

Fix snowbridge asset symbol matching 🔧 & Add e2e snapshot tests 🧪

---

packages/sdk-core/src/chains/Parachain.ts
packages/sdk/e2e/__snapshots__/xcm.test.ts.snap

Fixes Mythos teleport transfers

fix: Re-enable mythos

---

packages/sdk-core/src/chains/Parachain.ts
packages/sdk-core/src/chains/supported/BridgeHubPolkadot.test.ts
packages/sdk-core/src/chains/supported/BridgeHubPolkadot.ts
packages/sdk-core/src/chains/supported/Collectives.ts
packages/sdk-core/src/chains/supported/CoretimePolkadot.test.ts
packages/sdk-core/src/chains/supported/CoretimePolkadot.ts
packages/sdk-core/src/chains/supported/PeoplePolkadot.ts
packages/sdk-core/src/transfer/utils/validateAssetSupport.ts

fix: Re-enable system chains

---

apps/visualizer-be/scripts/channels.py
apps/visualizer-be/scripts/messages.py

Closes #
---
- Bug description:
- Fix summary:
---
---
Polkadot Asset Hub Address: `INSERT_ADDRESS_HERE`
> ⚠️ **Important:**  
> Do **NOT** provide a centralized exchange (CEX) address (e.g., Kraken, Binance, etc.).  
> Rewards sent to CEX addresses **may be lost** and are **not recoverable**.
---

fix(visualizer): Add request rate limit to subscan API calls

---

apps/visualizer-fe/src/components/AccountSelectModal/AccountSelectModal.tsx
apps/visualizer-fe/src/components/AccountsAmountPlot/AccountsAmountPlot.container.tsx
apps/visualizer-fe/src/components/AccountsAmountPlot/AccountsAmountPlot.tsx
apps/visualizer-fe/src/components/AmountTransferedPlot/AmountTransferedPlot.container.tsx
apps/visualizer-fe/src/components/AmountTransferedPlot/AmountTransferedPlot.tsx
apps/visualizer-fe/src/components/AmountTransferedPlot/CustomChartTooltip/CustomChartTooltip.tsx
apps/visualizer-fe/src/components/AssetsTransferedPlot/AssetsTransferedPlot.container.tsx
apps/visualizer-fe/src/components/AssetsTransferedPlot/utils/aggregateDataByParachain.ts
apps/visualizer-fe/src/components/ChannelInfo/ChannelAlert.container.tsx
apps/visualizer-fe/src/components/ChannelInfo/ChannelAlert.tsx
apps/visualizer-fe/src/components/DateRangePicker.tsx
apps/visualizer-fe/src/components/DownloadButtons.tsx
apps/visualizer-fe/src/components/ErrorAlert.tsx
apps/visualizer-fe/src/components/Footer/Footer.tsx
apps/visualizer-fe/src/components/Options/GeneralOptions.tsx
apps/visualizer-fe/src/components/Options/Options.tsx
apps/visualizer-fe/src/components/Options/OptionsModal.tsx
apps/visualizer-fe/src/components/Options/SkyboxUploadForm.tsx
apps/visualizer-fe/src/components/ParachainSelector.tsx
apps/visualizer-fe/src/components/SendXCMContainer/SendXCMContainer.tsx
apps/visualizer-fe/src/components/SendXcm/SendXcm.tsx
apps/visualizer-fe/src/components/SendXcm/SendXcmForm.tsx
apps/visualizer-fe/src/components/SliderInput.tsx
apps/visualizer-fe/src/components/SuccessMessagesPlot/CustomChartTooltip/CustomChartTooltip.tsx
apps/visualizer-fe/src/components/SuccessMessagesPlot/SuccessMessagesPlot.container.tsx
apps/visualizer-fe/src/components/SuccessMessagesPlot/SuccessMessagesPlot.tsx
apps/visualizer-fe/src/components/TabNavigator/TabNavigator.tsx
apps/visualizer-fe/src/locales/en/translation.json

feat(visualizer-fe): Improve localisation key structure

---

apps/visualizer-fe/package.json
apps/visualizer-fe/src/App.tsx
apps/visualizer-fe/src/components/EcosystemSelect/EcosystemSelect.container.tsx
apps/visualizer-fe/src/context/SelectedParachain/SelectedParachainContext.tsx
apps/visualizer-fe/src/hooks/useFilterSync.tsx
apps/visualizer-fe/src/routes/urlFilters.ts
pnpm-lock.yaml

feat(visualizer-fe): Add routing

---

apps/visualizer-fe/.env.example
apps/visualizer-fe/codegen.ts
apps/visualizer-fe/src/App.tsx
apps/visualizer-fe/vite.config.ts

Closes #
---
- Bug description:
- Fix summary:
---
---
Polkadot Asset Hub Address: `INSERT_ADDRESS_HERE`
> ⚠️ **Important:**  
> Do **NOT** provide a centralized exchange (CEX) address (e.g., Kraken, Binance, etc.).  
> Rewards sent to CEX addresses **may be lost** and are **not recoverable**.
---

fix(visualizer): Fix .env
